#!/usr/bin/python3 -i
import treegame
import atexit
import sys

if len(sys.argv) == 1:
    nplayers = 2
else:
    nplayers = int(sys.argv[1])

srv = treegame.Server(nplayers=nplayers)


srv.start()

atexit.register(srv.cleanup)

srv.listen()

srv.loop()
